[app]
    port=":8000"   # 项目启动端口
    env = "dev"    # 当前环境
    debug = "true" # 是否开启Debug
    apiVersion = "v1"  # 接口版本

[jwt]
    expireTime = 86400

[log]
    name = "go-cloud-native"  # 日志文件名
    level = "debug"           # 日志等级
    dir = "logs/applogs"      # 日志目录

[db]  # 数据库相关配置
    [db.cloud_native]          # mysql 组（这里可以扩展其他组）
        host = "47.88.105.38"  # mysql server 地址
        port = 13306           # mysql 链接端口
        user = "cloud_native"  # mysql 登录用户名
        pass = "ZOYk&#195t9OWZo~5+" # mysql 登录密码
        name = "cloud_native"  # mysql 当前使用库名
        maxIdleConn = 5        # 最大空闲链接数
        maxOpenConn = 10       # 最大并发链接数
        autoLoad = "true"      # 自动同步数据表
        debug = "false"        # 是否打开数据库DeBug
